import type { CompanyProfile } from "@/src/types/company";
import type { Matter } from "@/src/types/matter";
import type { PreparationItem } from "@/src/types/readiness";

export const preparationItems: PreparationItem[] = [
  {
    category: "Company structure",
    completed: 4,
    total: 5,
    summary: "Entity status, formation location, and current stage are captured.",
    nextStep: "Confirm registered address and tax contact.",
  },
  {
    category: "Founder alignment",
    completed: 3,
    total: 5,
    summary: "Roles and decision areas are mapped for the founding team.",
    nextStep: "Document unresolved role or vesting questions for counsel.",
  },
  {
    category: "Ownership information",
    completed: 2,
    total: 4,
    summary: "Current ownership notes are started but not fully organized.",
    nextStep: "Add issued equity, promised equity, and option pool assumptions.",
  },
  {
    category: "Intellectual property",
    completed: 3,
    total: 4,
    summary: "Core product assets and ownership sources are listed.",
    nextStep: "Flag any open-source, founder-created, or contractor-created work.",
  },
  {
    category: "Contractors and employees",
    completed: 2,
    total: 4,
    summary: "Known contributors are listed with rough work descriptions.",
    nextStep: "Add agreement status and payment history.",
  },
  {
    category: "Customer activity",
    completed: 3,
    total: 4,
    summary: "Pilot customers and revenue activity are summarized.",
    nextStep: "Add standard terms used with customers or prospects.",
  },
  {
    category: "Privacy and data practices",
    completed: 2,
    total: 5,
    summary: "Data collection and vendor notes are incomplete.",
    nextStep: "List user data categories, vendors, and current privacy promises.",
  },
  {
    category: "Fundraising preparation",
    completed: 2,
    total: 4,
    summary: "Fundraising goals and investor conversations are drafted.",
    nextStep: "Gather cap table assumptions and current fundraising materials.",
  },
  {
    category: "Corporate records",
    completed: 1,
    total: 4,
    summary: "The records inventory needs more source detail.",
    nextStep: "Add formation docs, approvals, consents, and tax records.",
  },
  {
    category: "Counsel readiness",
    completed: 3,
    total: 4,
    summary: "Open questions and priority matters are organized.",
    nextStep: "Choose the top three questions for the first counsel meeting.",
  },
];

export const companyProfile: CompanyProfile = {
  founderNames: "Maya Chen, Luis Romero",
  founderRoles: "CEO, product; CTO, engineering",
  founderEmails: "maya@northstar.example, luis@northstar.example",
  founderQuestions: "Discuss founder agreement topics and invention assignment records.",
  otherFounders: "Yes",
  ownershipDiscussed: "Yes",
  ownershipWrittenDown: "Partially",
  companyName: "Northstar Ledger",
  entityStatus: "Delaware C corporation, formed",
  entityType: "C corporation",
  formationLocation: "Austin, TX",
  expectedCustomerLocations: "United States",
  businessDescription:
    "Workflow software that helps small finance teams collect approval context before month-end close.",
  productOrService: "Approval workflow software for small finance teams.",
  developmentStage: "Pre-seed",
  revenueStatus: "One paid pilot",
  ownershipSummary: "Founder split is recorded with an intended option pool, but final grants need review.",
  ipSummary: "Product code, brand assets, and prototype materials are inventoried for counsel discussion.",
  contractorsSummary: "Two contractors supported design and backend setup. Agreement status needs confirmation.",
  customersExist: "Yes",
  contractorsUsed: "Yes",
  customerActivity: "Three design partners and one paid pilot are listed with current commercial terms.",
  personalInformationCollected: "Yes",
  regulatedIndustry: "No",
  operatesOutsideUs: "No",
  dataPractices: "The product collects business contact data and accounting workflow metadata.",
  expectsToRaise: "Yes",
  moneyAlreadyAccepted: "No",
  investorMeetingScheduled: "Yes",
  fundraisingTarget: "Pre-seed SAFE round",
  investorConversations: "Several warm investor conversations are active.",
  fundraisingMaterials: "Pitch deck, investor tracker, draft use of funds.",
  fundraisingTimeline: "Next quarter",
  outsideCounselExists: "No",
  priorityMatter: "Prepare founder and financing questions before counsel discussion.",
  counselQuestions: "What founder records and financing preparation materials should we organize first?",
  documentInventory: "Formation documents are present; board approvals and stock records need organization.",
  deadline: "Next quarter financing target",
  legalBudget: "Not provided",
  communicationFormat: "Virtual",
  meetingGoals: "Leave the first counsel meeting with a clear preparation checklist.",
  submittedAt: new Date(0).toISOString(),
};

export const matters: Matter[] = [
  {
    id: "founder-alignment",
    title: "Founder alignment and equity questions",
    type: "Organizing ownership information",
    status: "Information gathering",
    founderObjective: "Prepare founder role, vesting, and ownership questions before a counsel conversation.",
    description: "Founders want to organize current expectations and open ownership questions.",
    knownDeadline: "Before first counsel meeting",
    relevantPeople: "Maya Chen, Luis Romero",
    relatedDocuments: "Founder notes, draft cap table, formation documents",
    openQuestions: "What founder agreement topics should we discuss first? How should vesting and departure scenarios be framed?",
    missingInformation: "Final founder ownership notes and agreement status.",
    recommendedNextPreparationStep: "Write down current ownership assumptions and unresolved questions.",
    createdAt: new Date(0).toISOString(),
  },
  {
    id: "pilot-customer-terms",
    title: "Pilot customer terms",
    type: "Preparing for a customer contract",
    status: "Draft",
    founderObjective: "Organize current pilot commitments, pricing notes, and customer promises.",
    description: "Prepare customer context before discussing pilot terms.",
    knownDeadline: "Next customer conversation",
    relevantPeople: "Luis Romero",
    relatedDocuments: "Pilot email thread, pricing notes, security questionnaire",
    openQuestions: "Which customer promises should be clarified? What operational details should be captured?",
    missingInformation: "Standard terms and current customer commitments.",
    recommendedNextPreparationStep: "Summarize pilot terms and customer promises in one place.",
    createdAt: new Date(1).toISOString(),
  },
  {
    id: "fundraising-prep",
    title: "Pre-seed fundraising preparation",
    type: "Preparing for fundraising",
    status: "Ready for counsel review",
    founderObjective: "Collect fundraising assumptions and investor conversation context.",
    description: "Prepare financing context and records before counsel discussion.",
    knownDeadline: "Next quarter",
    relevantPeople: "Maya Chen",
    relatedDocuments: "Pitch deck, investor tracker, draft use of funds",
    openQuestions: "What financing structure questions should we prioritize? What company records will counsel likely request?",
    missingInformation: "Final fundraising target and investor timeline.",
    recommendedNextPreparationStep: "Gather financing materials and current company records.",
    createdAt: new Date(2).toISOString(),
  },
];

export const adminQueue = [
  { company: "Northstar Ledger", request: "Attorney matching", status: "New", owner: "Unassigned" },
  { company: "BrightDock Labs", request: "Counsel packet review", status: "In progress", owner: "Admin" },
  { company: "Fieldnote AI", request: "Matter setup support", status: "Waiting on founder", owner: "Ops" },
];
